# Generated by Django 6.0.1 on 2026-02-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='pagbank_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
