# Generated by Django 6.0.1 on 2026-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_mensalidade_pagbank_charge_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalidade',
            old_name='pagbank_charge_id',
            new_name='asaas_customer_id',
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
