# Generated by Django 6.0.1 on 2026-05-23 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_rename_pagbank_charge_id_mensalidade_asaas_customer_id_and_more'),
        ('usuarios', '0015_adicionar_campos_financeiros_aluna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mensalidade',
            constraint=models.UniqueConstraint(fields=('aluna', 'mes_referencia'), name='unique_mensalidade_aluna_mes_referencia'),
        ),
    ]
