# Generated by Django 6.0.1 on 2026-08-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_adicionar_constraint_mensalidade_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='data_ultimo_aviso',
            field=models.DateField(blank=True, null=True, verbose_name='Data do último aviso enviado'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='ultimo_aviso_enviado',
            field=models.CharField(blank=True, choices=[('vencimento_amanha', 'Aviso 1 dia antes do vencimento'), ('vencimento_hoje', 'Aviso no dia do vencimento'), ('atraso_1', 'Atraso - dia 1'), ('atraso_3', 'Atraso - dia 3'), ('atraso_7', 'Atraso - dia 7'), ('atraso_15', 'Atraso - dia 15'), ('atraso_30', 'Atraso - dia 30')], max_length=30, null=True, verbose_name='Último aviso de WhatsApp enviado'),
        ),
    ]
