# Generated by Django 6.0.1 on 2026-03-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espetaculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField()),
                ('data_apresentacao', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='espetaculos/')),
                ('audicao_aberta', models.BooleanField(default=False)),
                ('audicao_data_inicio', models.DateField(blank=True, null=True)),
                ('audicao_data_fim', models.DateField(blank=True, null=True)),
                ('audicao_instrucoes', models.TextField(blank=True)),
                ('venda_aberta', models.BooleanField(default=False)),
                ('venda_data_inicio', models.DateField(blank=True, null=True)),
                ('preco_ingresso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espetáculo',
                'verbose_name_plural': 'Espetáculos',
                'ordering': ['-data_apresentacao'],
            },
        ),
    ]
