# Generated by Django 6.0.1 on 2026-03-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espetaculo',
            name='arquivo_informacoes',
            field=models.FileField(blank=True, help_text='PDF com sinopse, personagens, audição, etc.', null=True, upload_to='espetaculos/pdfs/'),
        ),
    ]
