# Generated by Django 6.0.1 on 2026-04-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0002_espetaculo_arquivo_informacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoAudicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Whatsapp')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('personagens', models.CharField(max_length=200, verbose_name='Personagens escolhidos')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False, verbose_name='Inscrição lida')),
                ('espetaculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='espetaculo.espetaculo')),
            ],
            options={
                'verbose_name': 'Inscrição para Audição',
                'verbose_name_plural': 'Inscrições para Audição',
                'ordering': ['-data_inscricao'],
            },
        ),
    ]
