# Generated by Django 6.0.1 on 2026-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0003_inscricaoaudicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricaoaudicao',
            name='personagens',
            field=models.CharField(max_length=500, verbose_name='Personagens escolhidos'),
        ),
    ]
