# Generated by Django 6.0.1 on 2026-04-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0004_alter_inscricaoaudicao_personagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='espetaculo',
            name='arquivo_edital',
            field=models.FileField(blank=True, help_text='PDF com edital, regulamento ou material de apoio', null=True, upload_to='espetaculos/editais/'),
        ),
    ]
