# Generated by Django 6.0.1 on 2026-05-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0005_espetaculo_arquivo_edital'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAudicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(max_length=100)),
                ('nome_participante', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('regular', 'Regular'), ('bom', 'Bom'), ('muito_bom', 'Muito Bom'), ('excelente', 'Excelente'), ('destaque', 'Destaque')], default='regular', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='espetaculo.inscricaoaudicao')),
            ],
            options={
                'verbose_name': 'Avaliação de Audição',
                'verbose_name_plural': 'Avaliações de Audição',
            },
        ),
    ]
