# Generated by Django 6.0.1 on 2026-05-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0006_avaliacaoaudicao'),
        ('usuarios', '0015_adicionar_campos_financeiros_aluna'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacaoEspetaculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_dancar', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_espetaculo', to='usuarios.aluna')),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='espetaculo.espetaculo')),
            ],
            options={
                'verbose_name': 'Participação no espetáculo',
                'verbose_name_plural': 'Participações no espetáculo',
                'unique_together': {('espetaculo', 'aluna')},
            },
        ),
        migrations.CreateModel(
            name='CobrancaEspetaculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('taxa_palco', 'Taxa de palco'), ('figurino', 'Figurino')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('permitir_parcelamento', models.BooleanField(default=False)),
                ('max_parcelas', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='espetaculo.participacaoespetaculo')),
            ],
            options={
                'verbose_name': 'Cobrança do espetáculo',
                'verbose_name_plural': 'Cobranças do espetáculo',
            },
        ),
        migrations.CreateModel(
            name='ParcelaCobrancaEspetaculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField()),
                ('total_parcelas', models.PositiveIntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('mes_liberacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('codigo_pix', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='espetaculo.cobrancaespetaculo')),
            ],
            options={
                'verbose_name': 'Parcela da cobrança do espetáculo',
                'verbose_name_plural': 'Parcelas da cobrança do espetáculo',
                'ordering': ['numero_parcela'],
                'unique_together': {('cobranca', 'numero_parcela')},
            },
        ),
    ]
