# Generated by Django 6.0.1 on 2026-05-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0007_participacaoespetaculo_cobrancaespetaculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancaespetaculo',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cobrancaespetaculo',
            name='billing_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cobrancaespetaculo',
            name='enviado_asaas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cobrancaespetaculo',
            name='vencimento_primeira_parcela',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='asaas_bank_slip_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='asaas_installment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='asaas_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='asaas_nosso_numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='asaas_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='asaas_transaction_receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='billing_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
