# Generated by Django 6.0.1 on 2026-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0008_cobrancaespetaculo_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancaespetaculo',
            name='desconto_irmaos',
            field=models.BooleanField(default=False, help_text='Aplicar desconto especial para irmãos/irmãs'),
        ),
    ]
