# Generated by Django 6.0.1 on 2026-06-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0009_cobrancaespetaculo_desconto_irmaos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancaespetaculo',
            name='valor_figurino_avista',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha apenas para cobranças do tipo figurino.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cobrancaespetaculo',
            name='valor_figurino_parcelado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha apenas para cobranças do tipo figurino parcelado.', max_digits=10, null=True),
        ),
    ]
