# Generated by Django 6.0.1 on 2026-06-16 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0010_cobrancaespetaculo_valor_figurino_avista_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espetaculo',
            options={'ordering': ['-data_apresentacao'], 'verbose_name': 'Espetáculo / Evento', 'verbose_name_plural': 'Espetáculos / Eventos'},
        ),
        migrations.AddField(
            model_name='espetaculo',
            name='arquivo_divulgacao',
            field=models.FileField(blank=True, help_text='Arquivo de divulgação: PNG, JPG, JPEG ou PDF', null=True, upload_to='eventos/divulgacao/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='espetaculo',
            name='publico',
            field=models.BooleanField(default=True, help_text='Desmarque para eventos privados', verbose_name='Aberto ao público'),
        ),
        migrations.AddField(
            model_name='espetaculo',
            name='tipo',
            field=models.CharField(choices=[('espetaculo', 'Espetáculo'), ('evento', 'Evento')], default='espetaculo', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PedidoIngressoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_pix', models.TextField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_ingresso', to='espetaculo.espetaculo')),
            ],
            options={
                'verbose_name': 'Pedido de ingresso',
                'verbose_name_plural': 'Pedidos de ingressos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IngressoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=50, unique=True)),
                ('nome_participante', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('usado', 'Usado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='espetaculo.espetaculo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='espetaculo.pedidoingressoevento')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
