# Generated by Django 6.0.1 on 2026-06-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0011_alter_espetaculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espetaculo',
            name='imagem_ingresso',
            field=models.ImageField(blank=True, help_text='Imagem base usada para compor o ingresso com QR Code', null=True, upload_to='eventos/ingressos/'),
        ),
        migrations.AddField(
            model_name='ingressoevento',
            name='imagem_ingresso',
            field=models.ImageField(blank=True, null=True, upload_to='ingressos/finais/'),
        ),
        migrations.AddField(
            model_name='ingressoevento',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='ingressos/qrcodes/'),
        ),
        migrations.AddField(
            model_name='ingressoevento',
            name='validado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoingressoevento',
            name='asaas_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoingressoevento',
            name='asaas_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoingressoevento',
            name='qr_code_pix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingressoevento',
            name='codigo_unico',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidoingressoevento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=20),
        ),
    ]
