# Generated by Django 6.0.1 on 2026-07-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0012_espetaculo_imagem_ingresso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espetaculo',
            name='permite_ingresso_gratuito_aluna',
            field=models.BooleanField(default=False, help_text='Se marcado, alunas logadas poderão gerar ingresso sem pagamento.', verbose_name='Ingresso gratuito para alunas'),
        ),
    ]
