# Generated by Django 6.0.1 on 2026-07-06 23:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0013_espetaculo_permite_ingresso_gratuito_aluna'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='forma_pagamento_manual',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='observacao_pagamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelacobrancaespetaculo',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='parcelacobrancaespetaculo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
    ]
