# Generated by Django 6.0.1 on 2026-07-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0014_parcelacobrancaespetaculo_forma_pagamento_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancaespetaculo',
            name='sem_desconto',
            field=models.BooleanField(default=False, help_text='Se marcado, ignora os descontos automáticos e usa o valor exato lançado, tanto à vista quanto parcelado.', verbose_name='Sem desconto (à vista e parcelado)'),
        ),
    ]
