# Generated by Django 6.0.1 on 2026-08-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0015_cobrancaespetaculo_sem_desconto'),
        ('usuarios', '0016_aluna_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='ID do assento vindo do JSON (ex: A1, A2).', max_length=20)),
                ('setor', models.CharField(blank=True, max_length=50)),
                ('fileira', models.CharField(max_length=10)),
                ('numero', models.PositiveIntegerField()),
                ('x_pct', models.DecimalField(decimal_places=2, help_text='Posição horizontal em porcentagem (0 a 100) sobre a imagem do mapa.', max_digits=6)),
                ('y_pct', models.DecimalField(decimal_places=2, help_text='Posição vertical em porcentagem (0 a 100) sobre a imagem do mapa.', max_digits=6)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado_temporario', 'Reservado temporariamente'), ('vendido', 'Vendido'), ('bloqueado_manual', 'Bloqueado manualmente')], default='disponivel', max_length=25)),
                ('reservado_em', models.DateTimeField(blank=True, help_text='Momento em que a reserva temporária começou.', null=True)),
                ('reservado_por_sessao', models.CharField(blank=True, help_text='Identificador da sessão/comprador que reservou temporariamente.', max_length=100, null=True)),
                ('bloqueado_motivo', models.CharField(blank=True, help_text='Motivo do bloqueio manual (ex: patrocinador, família).', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assento',
                'verbose_name_plural': 'Assentos',
                'ordering': ['fileira', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='espetaculo',
            name='exige_login_para_compra',
            field=models.BooleanField(default=False, help_text='Se marcado, apenas usuários autenticados podem comprar ingressos deste evento.', verbose_name='Exigir login para comprar ingresso'),
        ),
        migrations.AddField(
            model_name='espetaculo',
            name='venda_com_assentos_numerados',
            field=models.BooleanField(default=False, help_text='Se marcado, exibe o mapa de assentos para escolha no momento da compra.', verbose_name='Venda com assentos numerados'),
        ),
        migrations.AddField(
            model_name='ingressoevento',
            name='assento',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas quando o evento usa venda com assentos numerados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingressos', to='espetaculo.assento'),
        ),
        migrations.CreateModel(
            name='MapaAssentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_mapa', models.ImageField(blank=True, help_text='Imagem de fundo do teatro/salão usada no mapa.', null=True, upload_to='espetaculos/mapas_assentos/')),
                ('largura_original', models.PositiveIntegerField(default=1600, help_text='Largura original (em pixels) usada para gerar as coordenadas.')),
                ('altura_original', models.PositiveIntegerField(default=1200, help_text='Altura original (em pixels) usada para gerar as coordenadas.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapa_assentos', to='espetaculo.espetaculo')),
            ],
            options={
                'verbose_name': 'Mapa de assentos',
                'verbose_name_plural': 'Mapas de assentos',
            },
        ),
        migrations.AddField(
            model_name='assento',
            name='mapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assentos', to='espetaculo.mapaassentos'),
        ),
        migrations.CreateModel(
            name='IngressoGratuitoAluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos_gratuitos', to='usuarios.aluna')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos_gratuitos_alunas', to='espetaculo.espetaculo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos_gratuitos_aluna', to='espetaculo.pedidoingressoevento')),
            ],
            options={
                'verbose_name': 'Ingresso gratuito de aluna',
                'verbose_name_plural': 'Ingressos gratuitos de alunas',
                'unique_together': {('aluna', 'evento')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='assento',
            unique_together={('mapa', 'identificador')},
        ),
    ]
