# Generated by Django 6.0.1 on 2026-08-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0016_assento_espetaculo_exige_login_para_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingressoevento',
            name='gratuito',
            field=models.BooleanField(default=False, verbose_name='Ingresso gratuito'),
        ),
        migrations.AddField(
            model_name='pedidoingressoevento',
            name='assentos_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='IDs dos assentos'),
        ),
        migrations.AddField(
            model_name='pedidoingressoevento',
            name='quantidade_gratuita',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de ingressos gratuitos'),
        ),
    ]
