# Generated by Django 6.0.1 on 2026-09-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0017_ingressoevento_gratuito_and_more'),
        ('usuarios', '0016_aluna_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquiagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('maquiadora', models.CharField(max_length=120, verbose_name='Maquiadora')),
                ('duracao_minutos', models.PositiveIntegerField(verbose_name='Duração (minutos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquiagens', to='usuarios.aluna')),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquiagens', to='espetaculo.espetaculo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquiagens', to='usuarios.turma')),
            ],
            options={
                'verbose_name': 'Maquiagem',
                'verbose_name_plural': 'Maquiagens',
                'ordering': ['horario'],
            },
        ),
    ]
