# Generated by Django 6.0.1 on 2026-09-09 22:46

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0018_maquiagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espetaculo',
            name='arquivo_divulgacao',
            field=models.FileField(blank=True, help_text='Arquivo de divulgação: PNG, JPG, JPEG ou PDF', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='eventos/divulgacao/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='espetaculo',
            name='arquivo_edital',
            field=models.FileField(blank=True, help_text='PDF com edital, regulamento ou material de apoio', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='espetaculos/editais/'),
        ),
        migrations.AlterField(
            model_name='espetaculo',
            name='arquivo_informacoes',
            field=models.FileField(blank=True, help_text='PDF com sinopse, personagens, audição, etc.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='espetaculos/pdfs/'),
        ),
    ]
