# Generated by Django 6.0.1 on 2026-09-11 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0019_alter_espetaculo_arquivo_divulgacao_and_more'),
        ('usuarios', '0016_aluna_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMaquiagemTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquiadora', models.CharField(max_length=120, verbose_name='Maquiadora')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder o botão de agendamento dessa turma.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_maquiagem', to='espetaculo.espetaculo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_maquiagem', to='usuarios.turma')),
            ],
            options={
                'verbose_name': 'Agenda de maquiagem da turma',
                'verbose_name_plural': 'Agendas de maquiagem das turmas',
                'unique_together': {('espetaculo', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='HorarioMaquiagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(verbose_name='Data e horário')),
                ('duracao_minutos', models.PositiveIntegerField(default=30, verbose_name='Duração (minutos)')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado_temporario', 'Reservado temporariamente'), ('agendado', 'Agendado'), ('bloqueado_manual', 'Bloqueado manualmente')], default='disponivel', max_length=25)),
                ('reservado_em', models.DateTimeField(blank=True, null=True)),
                ('reservado_por_sessao', models.CharField(blank=True, max_length=100, null=True)),
                ('bloqueado_motivo', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='espetaculo.agendamaquiagemturma')),
            ],
            options={
                'verbose_name': 'Horário de maquiagem',
                'verbose_name_plural': 'Horários de maquiagem',
                'ordering': ['horario'],
                'unique_together': {('agenda', 'horario')},
            },
        ),
        migrations.CreateModel(
            name='AgendamentoMaquiagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('maquiagem', 'Maquiagem'), ('cabelo', 'Cabelo'), ('cabelo_e_maquiagem', 'Cabelo e Maquiagem')], max_length=25)),
                ('criado_por_admin', models.BooleanField(default=False, help_text='True quando o agendamento foi feito pelo admin em nome da aluna.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_maquiagem', to='usuarios.aluna')),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='espetaculo.horariomaquiagem')),
            ],
            options={
                'verbose_name': 'Agendamento de maquiagem',
                'verbose_name_plural': 'Agendamentos de maquiagem',
                'ordering': ['horario__horario'],
            },
        ),
        migrations.DeleteModel(
            name='Maquiagem',
        ),
    ]
