# Generated by Django 6.0.1 on 2026-09-21 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espetaculo', '0020_agendamaquiagemturma_horariomaquiagem_and_more'),
        ('usuarios', '0017_turma_faixa_etaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_vagas', models.PositiveSmallIntegerField(default=1, help_text='Quantas alunas/alunos interpretam esse personagem (normalmente 1).', verbose_name='Número de vagas')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='espetaculo.espetaculo')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('espetaculo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ElencoPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('aluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens_elenco', to='usuarios.aluna')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenco', to='espetaculo.personagem')),
            ],
            options={
                'verbose_name': 'Elenco do personagem',
                'verbose_name_plural': 'Elenco dos personagens',
                'unique_together': {('personagem', 'aluna')},
            },
        ),
    ]
