# Generated by Django 6.0.1 on 2026-09-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo_hero', models.CharField(blank=True, default='Transformando sonhos em movimento', max_length=150, verbose_name='Frase de destaque (abaixo do nome da escola)')),
                ('texto_sobre', models.TextField(blank=True, default='Em breve em novo endereço', verbose_name='Texto da seção "Sobre"')),
                ('endereco', models.CharField(blank=True, default='Praça Cel. João Rosa, 176 - Sobreloja - Centro, Piedade - SP', max_length=200, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, default='15 99751-7185', max_length=30, verbose_name='Telefone')),
                ('email_contato', models.EmailField(blank=True, default='berkana.arte.magia@gmail.com', max_length=254, verbose_name='E-mail de contato exibido no site')),
            ],
            options={
                'verbose_name': 'Configuração da escola',
                'verbose_name_plural': 'Configuração da escola',
            },
        ),
    ]
