# Generated by Django 6.0.1 on 2026-05-12 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_aula'),
        ('usuarios', '0012_turma_dia_semana_turma_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.turma', verbose_name='Turma/Aula escolhida'),
        ),
    ]
