# Generated by Django 6.0.1 on 2026-08-03 22:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agendamento_aula'),
        ('usuarios', '0016_aluna_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='aluna_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_experimentais', to='usuarios.aluna', verbose_name='Aluna vinculada (se já for aluna Bailah)'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='evento_calendario_criado',
            field=models.BooleanField(default=True, verbose_name='Evento criado no Google Agenda'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('pendente', 'Pagamento pendente'), ('pago', 'Pago')], default='pago', max_length=20, verbose_name='Status do pagamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor da aula experimental'),
        ),
    ]
