# Generated by Django 6.0.1 on 2026-08-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_agendamento_aluna_vinculada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha_gratuita_ativa', models.BooleanField(default=False, verbose_name='Campanha de aula experimental gratuita ativa')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Agendamento',
                'verbose_name_plural': 'Configurações de Agendamento',
            },
        ),
    ]
