# Generated by Django 6.0.1 on 2026-08-03 23:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_configuracaoagendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoagendamento',
            name='valor_aula_experimental',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10, verbose_name='Valor da aula experimental'),
        ),
    ]
