# Generated by Django 6.0.1 on 2026-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_configuracaoagendamento_valor_aula_experimental'),
        ('usuarios', '0016_aluna_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoagendamento',
            name='turmas_gratuitas',
            field=models.ManyToManyField(blank=True, help_text='Se nenhuma turma for selecionada e a campanha estiver ativa, todas as turmas ficam gratuitas.', related_name='configuracoes_gratuitas', to='usuarios.turma', verbose_name='Turmas participantes da campanha gratuita'),
        ),
    ]
