# Generated by Django 6.0.1 on 2026-08-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_configuracaoagendamento_turmas_gratuitas'),
        ('usuarios', '0016_aluna_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoagendamento',
            name='turmas_gratuitas',
            field=models.ManyToManyField(blank=True, related_name='configuracoes_campanha_gratuita', to='usuarios.turma', verbose_name='Turmas gratuitas'),
        ),
    ]
