# Generated by Django 6.0.1 on 2026-09-17 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_configuracaoagendamento_turmas_gratuitas'),
        ('usuarios', '0016_aluna_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='aluna_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_experimentais', to='usuarios.aluna', verbose_name='Aluna vinculada (se já for aluna da escola)'),
        ),
    ]
