# Generated by Django 6.0.1 on 2026-03-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_recuperacaosenha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluna',
            options={'ordering': ['nome'], 'verbose_name': 'Aluna', 'verbose_name_plural': 'Alunas'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AddField(
            model_name='recuperacaosenha',
            name='codigo_sms',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
