# Generated by Django 6.0.1 on 2026-03-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_aluna_options_alter_perfil_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recuperacaosenha',
            options={'verbose_name': 'Recuperacao de Senha', 'verbose_name_plural': 'Recuperacoes de Senha'},
        ),
        migrations.RemoveField(
            model_name='recuperacaosenha',
            name='codigo_sms',
        ),
    ]
