# Generated by Django 6.0.1 on 2026-03-30 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_recuperacaosenha_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('horario', models.CharField(blank=True, help_text='Ex: Segunda e Quarta 14h-15h', max_length=100)),
                ('professor', models.CharField(blank=True, max_length=100)),
                ('capacidade_maxima', models.IntegerField(default=20, help_text='Número máximo de alunas')),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='aluna',
            name='turma_atual',
        ),
        migrations.AddField(
            model_name='aluna',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunas', to='usuarios.turma'),
        ),
    ]
