# Generated by Django 6.0.1 on 2026-04-02 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_turma_remove_aluna_turma_atual_aluna_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluna',
            options={},
        ),
        migrations.AddField(
            model_name='aluna',
            name='tipo_aluna',
            field=models.CharField(choices=[('infantil', 'Infantil (com responsável)'), ('adulto', 'Adulto (sem responsável)')], default='infantil', max_length=20),
        ),
        migrations.AlterField(
            model_name='aluna',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunas', to=settings.AUTH_USER_MODEL),
        ),
    ]
