# Generated by Django 6.0.1 on 2026-04-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_aluna_options_aluna_tipo_aluna_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluna',
            options={'ordering': ['nome'], 'verbose_name': 'Aluna', 'verbose_name_plural': 'Alunas'},
        ),
    ]
