# Generated by Django 6.0.1 on 2026-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_aluna_data_nascimento_alter_perfil_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluna',
            name='turma',
        ),
        migrations.AddField(
            model_name='aluna',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='alunas', to='usuarios.turma'),
        ),
    ]
