# Generated by Django 6.0.1 on 2026-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_aluna_turma_aluna_turmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_responsavel',
            field=models.BooleanField(default=True),
        ),
    ]
