# Generated by Django 6.0.1 on 2026-05-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_aluna_genero_perfil_genero_perfil_is_tambem_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sábado', 'Sábado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='tipo',
            field=models.CharField(choices=[('turma', 'Turma'), ('aula_experimental', 'Aula Experimental')], default='turma', max_length=20),
        ),
    ]
