# Generated by Django 6.0.1 on 2026-05-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_turma_professor_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='disponivel_experimental',
            field=models.BooleanField(default=True, verbose_name='Disponível para aula experimental'),
        ),
    ]
