# Generated by Django 6.0.1 on 2026-05-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_turma_disponivel_experimental'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluna',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Dia do vencimento'),
        ),
        migrations.AddField(
            model_name='aluna',
            name='gerar_mensalidade_automatica',
            field=models.BooleanField(default=True, verbose_name='Gerar mensalidade automática'),
        ),
        migrations.AddField(
            model_name='aluna',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor base da mensalidade'),
        ),
    ]
