# Generated by Django 6.0.1 on 2026-09-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_aluna_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='faixa_etaria',
            field=models.CharField(blank=True, help_text='Ex: 3 a 5 anos (aparece no card da turma no site)', max_length=50),
        ),
    ]
