# Generated by Django 6.0.1 on 2026-02-10 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('geral', 'Geral'), ('evento', 'Evento'), ('feriado', 'Feriado'), ('reposicao', 'Reposição'), ('apresentacao', 'Apresentação')], default='geral', max_length=20)),
                ('data_evento', models.DateField(blank=True, help_text='Data do evento (se aplicável)', null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
