# Generated by Django 6.0.1 on 2026-09-16 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario_avisos', '0001_initial'),
        ('usuarios', '0016_aluna_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='alunas',
            field=models.ManyToManyField(blank=True, related_name='avisos_diretos', to='usuarios.aluna', verbose_name='Alunas destinatárias'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='professoras',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Professores'}, related_name='avisos_professora', to=settings.AUTH_USER_MODEL, verbose_name='Professoras destinatárias'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='turmas',
            field=models.ManyToManyField(blank=True, help_text='Deixe vazio junto com Alunas e Professoras para exibir para todas.', related_name='avisos', to='usuarios.turma', verbose_name='Turmas destinatárias'),
        ),
    ]
