# Generated by Django 6.0.1 on 2026-09-16 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario_avisos', '0002_aviso_alunas_aviso_professoras_aviso_turmas'),
        ('usuarios', '0016_aluna_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='alunas',
            field=models.ManyToManyField(blank=True, help_text='Use quando o aviso for para alunas específicas, além ou em vez das turmas.', related_name='avisos_diretos', to='usuarios.aluna', verbose_name='Alunas destinatárias'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='professoras',
            field=models.ManyToManyField(blank=True, help_text='Professoras que devem ver este aviso mesmo sem serem alunas da turma.', limit_choices_to={'groups__name': 'Professores'}, related_name='avisos_professora', to=settings.AUTH_USER_MODEL, verbose_name='Professoras destinatárias'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='turmas',
            field=models.ManyToManyField(blank=True, help_text='Deixe em branco junto com "Alunas" e "Professoras" para exibir este aviso para todas.', related_name='avisos', to='usuarios.turma', verbose_name='Turmas destinatárias'),
        ),
    ]
