# Generated by Django 6.0.1 on 2026-09-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario_avisos', '0003_alter_aviso_alunas_alter_aviso_professoras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='enviar_whatsapp',
            field=models.BooleanField(default=False, help_text='Além de aparecer no site, manda mensagem de WhatsApp pros destinatários.', verbose_name='Enviar por WhatsApp também'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='horario',
            field=models.CharField(blank=True, help_text='Ex: 14h ou 14h às 16h', max_length=50, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='notificacao_dia_enviada',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='aviso',
            name='notificacao_semana_enviada',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
