# Generated by Django 6.0.1 on 2026-09-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario_avisos', '0004_aviso_enviar_whatsapp_aviso_horario_and_more'),
        ('espetaculo', '0021_personagem_elencopersonagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='personagens',
            field=models.ManyToManyField(blank=True, help_text='Avisa só quem está escalado nesses personagens (ex: ensaio só das protagonistas).', related_name='avisos', to='espetaculo.personagem', verbose_name='Personagens destinatários'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('geral', 'Geral'), ('evento', 'Evento'), ('feriado', 'Feriado'), ('reposicao', 'Reposição'), ('apresentacao', 'Apresentação'), ('ensaio', 'Ensaio')], default='geral', max_length=20),
        ),
    ]
