name: Gerar mensalidades

on:
  schedule:
    - cron: '0 11 20 * *'
  workflow_dispatch:

jobs:
  gerar-mensalidades:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Rodar geração no Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway run --service 736065af-4959-4b0f-8af3-7985d8d0fc33 python manage.py gerar_mensalidades