name: Gerar mensalidades

on:
  schedule:
    - cron: '0 11 20 * *'
  workflow_dispatch:

jobs:
  gerar-mensalidades:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      RAILWAY_PROJECT_ID: de264516-835b-4bc9-9bd9-11055c649742
      RAILWAY_ENVIRONMENT_ID: a69e8f02-c043-4cd8-88f2-0fb359ba64ef

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Railway CLI via npm
        run: npm install -g @railway/cli@latest

      - name: Verificar instalação
        run: railway --version

      - name: Rodar geração no Railway
        run: railway run --service 736065af-4959-4b0f-8af3-7985d8d0fc33 python manage.py gerar_mensalidades